spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/petshop
    username: root
    password: Theanh@123
#    password: Theanh@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
#  packages-to-scan:
#    - com.pet.controller

